#!/usr/bin/env node
// Install claude-agent-comm framework into a target project's .claude/
//
// Usage: node install.js <target-project-dir> [--force] [--codex]
//
// Options:
//   --force  overwrite existing files
//   --codex  also install .codex/config.toml with bridge path auto-resolved

const fs = require('fs');
const path = require('path');

const args = process.argv.slice(2);
const target = args.find(a => !a.startsWith('--'));
const force = args.includes('--force');
const withCodex = args.includes('--codex');

if (!target) {
  process.stderr.write(`usage: node install.js <target-project-dir> [--force] [--codex]\n`);
  process.exit(1);
}

const src = __dirname;
const dst = path.resolve(target);

if (!fs.existsSync(dst) || !fs.statSync(dst).isDirectory()) {
  process.stderr.write(`target not found or not a directory: ${dst}\n`);
  process.exit(1);
}

const hooksDst = path.join(dst, '.claude', 'hooks');
const commDst  = path.join(dst, '.claude', 'comm');
fs.mkdirSync(hooksDst, { recursive: true });
fs.mkdirSync(commDst,  { recursive: true });

function copy(from, to) {
  if (fs.existsSync(to) && !force) {
    console.log(`[skip] ${to} exists (use --force)`);
    return;
  }
  fs.copyFileSync(from, to);
  console.log(`[ok]   ${to}`);
}

function writeFileIfMissing(to, content, label) {
  if (fs.existsSync(to) && !force) {
    console.log(`[skip] ${to} exists (use --force)`);
    return;
  }
  fs.writeFileSync(to, content);
  console.log(`[ok]   ${to} ${label || ''}`);
}

// hooks/*.js
for (const name of fs.readdirSync(path.join(src, 'hooks'))) {
  if (!name.endsWith('.js')) continue;
  copy(path.join(src, 'hooks', name), path.join(hooksDst, name));
}

// comm/launch_child.js + CLAUDE.md
copy(path.join(src, 'comm', 'launch_child.js'), path.join(commDst, 'launch_child.js'));
copy(path.join(src, 'comm', 'CLAUDE.md'),       path.join(commDst, 'CLAUDE.md'));

// Optional: --codex 自动装 .codex/config.toml 并填入 bridge 绝对路径
if (withCodex) {
  const codexDst = path.join(dst, '.codex');
  fs.mkdirSync(codexDst, { recursive: true });
  const bridgePath = path.join(hooksDst, 'codex_hook_bridge.js').replace(/\\/g, '\\\\');
  const tomlContent =
    `# Generated by claude-agent-comm install.js --codex\n` +
    `notify = ["node", "${bridgePath}"]\n`;
  writeFileIfMissing(path.join(codexDst, 'config.toml'), tomlContent, '(auto-resolved bridge path)');
}

console.log('');
console.log('=== 完成 ===');
console.log('下一步手动：');
console.log(`  1. merge ${path.join(src, 'examples', 'settings.local.json.example')} 的 hooks 段到`);
console.log(`     ${path.join(dst, '.claude', 'settings.local.json')}`);
if (!withCodex) {
  console.log('  2. Codex 用户跑 --codex 自动装 .codex/config.toml（或手动 copy 模板）');
}
console.log('  3. 目标项目 .gitignore 加：');
console.log('     .claude/signals/');
